### ISSUE TITLE
Add quote.

### ISSUE THREAD

**Issue by Erwin-Iosef** [shlomif/fortune-mod#101]
Hey can you add this quote? Just thought it'd be cool to add.

"Deliverance from death does not come from an afterlife, but only with a smile accompanying acceptance of one's own cessation of existence. That one has seen enough of the world to finally let go of all that it has given him and set himself free. That is man's true and final salvation."

-Elbon Noteleks.

**Comment by shlomif** [comment]
@Erwin-Iosef : hi. I don't like this quote. Also see https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#see-also

**Comment by Erwin-Iosef** [comment]
Oh hey, thanks for replying. 
Understandable. In that case, a small request, would you be so kind to delete this issue please?

**Comment by shlomif** [comment]
Closing.

**Comment by Erwin-Iosef** [comment]
Hey thanks but, can't you delete it? I think only you can do that as project maintainer.

**Comment by Erwin-Iosef** [comment]
Just a personal request.
Regardless, you've made your point and yes it is a bit of insecurity 😅, thank you for shining that light on that problem.
