### ISSUE TITLE
Does unstr still make sense?

### ISSUE THREAD

**Issue by vromero** [shlomif/fortune-mod#12]
Back in the day when index and fortunes lived in the same file it made a lot of sense.

But lately I've been trying to use it and it always complain about the file format (?) plus I don't see the point of it anymore. Is there any valid use case for it?

**Comment by shlomif** [comment]
This reminds me of https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines . Anyway , I don't recall ever using unstr or understanding what it is all about, but I think building it does not do much harm. Is there any reason to avoid building and installing it?
