### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by joseh55** [shlomif/fortune-mod#13]
Hi! i have a system in english lang, but i need fortune in Spanish!!!! i already installed fortunes-es and there a included folder in /usr/share /games/fortunes/es buut no way to say fortune that only say in spanish lang. In the man of fortune is no information.. Very thanks

**Comment by shlomif** [comment]
Hi @joseh55 !

Reading from the C source code:

```c
            char *lang=NULL;

            lang=getenv("LC_ALL");
            if (!lang) lang=getenv("LC_MESSAGES");
            if (!lang) lang=getenv("LANGUAGE");
            if (!lang) lang=getenv("LANG");
            if (lang) {
                char llang[512];
                int ret=0;
```

try setting these environment variables - perhaps using a shell function - see https://duckduckgo.com/?q=bash+functions&ia=web .

**Comment by shlomif** [comment]
@joseh55 : ping.

**Comment by shlomif** [comment]
Closing due to lack of response. This issue can be reopened later if there is demand.
