### ISSUE TITLE
Wrong version number in release

### ISSUE THREAD

**Issue by kdex** [shlomif/fortune-mod#16]
The current `1.99.5` release still comes with the `1.99.4` version number:

```bash
$ fortune -v
fortune-mod version 1.99.4
```

I'm assuming that the version number should be taken from [ver.txt](https://github.com/shlomif/fortune-mod/blob/97d05a87ebc056b0fd1eed5665aeff93d749f610/fortune-mod/ver.txt), but instead, there's a hard-coded macro in [fortune.c](https://github.com/shlomif/fortune-mod/blob/97d05a87ebc056b0fd1eed5665aeff93d749f610/fortune-mod/fortune/fortune.c#L100).

Since this project is using CMake, you should rather define the version number directly within CMake and have it substitute the appropriate locations in your source files, see [here](https://cmake.org/cmake-tutorial/) for an example.

**Comment by shlomif** [comment]
Hi!

On Wed, 29 Nov 2017 21:50:30 -0800
kdex <notifications@github.com> wrote:

> The current `1.99.5` release still comes with the `1.99.4` version number:
> 
> ```bash
> $ fortune -v
> fortune-mod version 1.99.4
> ```
> 
> I'm assuming that the version number should be taken from
> [ver.txt](https://github.com/shlomif/fortune-mod/blob/97d05a87ebc056b0fd1eed5665aeff93d749f610/fortune-mod/ver.txt),
> but instead, there's a hard-coded macro in
> [fortune.c](https://github.com/shlomif/fortune-mod/blob/97d05a87ebc056b0fd1eed5665aeff93d749f610/fortune-mod/fortune/fortune.c#L100).
> 
> Since this project is using CMake, you should rather define the version
> number directly within CMake and have it substitute the appropriate locations
> in your source files, see [here](https://cmake.org/cmake-tutorial/) for an
> example.
> 

thanks for the report. I'll have cmake read ver.txt and generate an include
file with the version macro.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Summer Glau Facts - http://shlom.in/sglau-facts

There are at least 137 Larry Walls in the U.S., but only one that matters.
    — http://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Should be fixed in the latest commit - thanks!
