### ISSUE TITLE
Let's fix recode!

### ISSUE THREAD

**Issue by rrthomas** [shlomif/fortune-mod#19]
Surely in the same spirit as you have resurrected fortune-mod rather than find something else, we should fix recode's space leaks rather than find an alternative?

I have, as you can see, filed some issues here and with `Test::RunValgrind`, trying to build and run the tests of fortune-mod.

Currently I can't actually get the tests to run; if you can help with that, I'm happy to look at fixing librecode (I have plenty of experience both with Valgrind and with this kind of oldish C).

**Comment by shlomif** [comment]
Hi Reuben,

On Fri, 12 Jan 2018 05:50:04 -0800
Reuben Thomas <notifications@github.com> wrote:

> Surely in the same spirit as you have resurrected fortune-mod rather than
> find something else, we should fix recode's space leaks rather than find an
> alternative?
> 

librecode seems to be dead upstream and unmaintained - see
https://duckduckgo.com/?q=librecode&ia=web . If it will be easier to move to an
alternative with no issues, then I'd prefer it this way.

> I have, as you can see, filed some issues here and with `Test::RunValgrind`,
> trying to build and run the tests of fortune-mod.
> 
> Currently I can't actually get the tests to run; if you can help with that,
> I'm happy to look at fixing librecode (I have plenty of experience both with
> Valgrind and with this kind of oldish C).
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/open-source/projects/fortune-mod/

Fortran - there isn’t a way to do it... oh wait! Now there is.
    — http://www.shlomifish.org/humour/ways_to_do_it.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Closing for now as Wontfix/wishlist.
