### ISSUE TITLE
Move sources out of `fortune-mod`?

### ISSUE THREAD

**Issue by rrthomas** [shlomif/fortune-mod#20]
The organisation of the code is a little odd to my eyes: why not move everything in `fortune-mod` up a level, so you don't have this whole `fortune-mod/fortune-mod` thing going on? I think I see what happened: you dumped the original sources into a directory and slapped a `README.md` etc. on top; but that can be straightened out, don't you think?

**Comment by shlomif** [comment]
This is intentional to have a sub-directory structure that allows putting more stuff outside the main sources. There were previous issues filed for it. Resolving as NOTABUG.

**Comment by rrthomas** [comment]
OK, apologies for the duplication.
