### ISSUE TITLE
Problem with running valgrind tests

### ISSUE THREAD

**Issue by rrthomas** [shlomif/fortune-mod#21]
I tried to run the valgrind tests to see what is up with librecode, but having commented out the `plan skip_all` line, I got the following error when I ran the tests:

    /home/rrt/repo/fortune-mod/fortune-mod/tests/t/valgrind.t ................ Error open (<:raw:encoding(UTF-8)) on 'fortune--1.valgrind-log': No such file or directory at /home/rrt/.local/share/perl/5.22.1/Test/RunValgrind.pm line 74.

**Comment by shlomif** [comment]
It should be fixed in a recent commit, thanks! I had the wrong path to the fortune exe there. Note that the test will succeed if you don't "make install" first.

**Comment by shlomif** [comment]
Closing for now to avoid clutter.

**Comment by rrthomas** [comment]
Now, having updated, rebuilt and run `make install`, I get the following error during `make check`:

    /home/rrt/.local/var/repo/fortune-mod/fortune-mod/tests/t/valgrind.t ................ Error open (<:unix) on 'fortune--1.valgrind-log': No such file or directory at /home/rrt/.local/lib/perl5/Test/RunValgrind.pm line 74.

**Comment by rrthomas** [comment]
Apologies, I had actually failed to update, owing to a merge conflict.
