### ISSUE TITLE
Underflow error with Tbl.str_shortlen in strfile.c

### ISSUE THREAD

**Issue by pouar** [shlomif/fortune-mod#24]
Seems to have been introduced in 082e4c0b980313f

**Comment by pouar** [comment]
btw, the end result is that strfile thinks the shortest string is way bigger than the longest string.

**Comment by shlomif** [comment]
On Tue, 20 Mar 2018 22:49:35 +0000 (UTC)
pouar <notifications@github.com> wrote:

> Seems to have been introduced in 082e4c0b980313f
> 

thanks for the report! I'll investigate it.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/

The English Wikipedia: now you don’t see it — now you do.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi! Please let me know if commit f7c9256a4656571d2c6824983dcbc32294f73858 fixes the problem for you.

**Comment by pouar** [comment]
seems to

**Comment by shlomif** [comment]
On Wed, 21 Mar 2018 23:32:46 +0000 (UTC)
pouar <notifications@github.com> wrote:

> Closed #24.
> 

thanks for the headsup and for verifying! 


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
NSA Factoids - http://www.shlomifish.org/humour/bits/facts/NSA/

Chuck Norris helps the gods that help themselves.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
