### ISSUE TITLE
Confict in numbering of great moments in history

### ISSUE THREAD

**Issue by adnidor** [shlomif/fortune-mod#28]
https://github.com/shlomif/fortune-mod/blob/eeea80856c35f1e4487eed3e59829539eb12c07b/fortune-mod/datfiles/food#L232
https://github.com/shlomif/fortune-mod/blob/6c989cba8104c7d1264f1d2d8283306c70930317/fortune-mod/datfiles/science#L933

Both fortunes have the same number (7) but a different content.

Solution would probably be to change one of the numbers.

**Comment by Pedro-Mendes** [comment]
I did a search on the whole folder from this repo and only found just 5 "GREAT MOMENT" quotes, is there a logical number for the id? I am wondering because as @adnidor said there are two '7's and there is a #21 from american history. How if there are only 5 quotes related to great moments?

Thanks!

**Comment by shlomif** [comment]
Should be fixed and released - thanks!
