### ISSUE TITLE
1.99.3 tarball hasn't been cleaned

### ISSUE THREAD

**Issue by atsampson** [shlomif/fortune-mod#3]
The `fortune-mod-1.99.3.tar.xz` tarball hasn't had "make clean" run on it beforehand -- so it contains object files, timestamp files, etc. This will cause strange build failures.

It would be a good idea to automate the process of building the tarball to prevent this kind of problem (automake would provide "make dist"; I assume CMake has something equivalent).

**Comment by shlomif** [comment]
The comment by email didn't arrive so I'm posting it here:


Hi Adam,

On Thu, 29 Dec 2016 13:02:28 -0800
Adam Sampson <notifications@github.com> wrote:

> The `fortune-mod-1.99.3.tar.xz` tarball hasn't had "make clean" run on it
> beforehand -- so it contains object files, timestamp files, etc. This will
> cause strange build failures.
>   

Point taken, but note that if you do an out-of-directory "cmake /path/to/src ;
make ; make install" build, then there should not be a problem. I will still
correct the problem in the next release.

> It would be a good idea to automate the process of building the tarball to
> prevent this kind of problem (automake would provide "make dist"; I assume
> CMake has something equivalent).
>   

I used CMake's "make package_source" which is equivalent, but I guess I didn't
run "git clean -dxf" first or purged the artefacts of the old build system.
I'll try to see what I can do.

Thanks!

	— Shlomi

**Comment by shlomif** [comment]
Fixed in 1.99.4 and tweaked .gitignore to avoid ignoring these files to prevent future problems. Closing - thanks!
