### ISSUE TITLE
Move strfile and unstr (back) to /usr/bin/ (instead of /usr/sbin/)

### ISSUE THREAD

**Issue by cboltz** [shlomif/fortune-mod#35]
Since at least *) 2.6.2, strfile and unstr get installed to /usr/sbin/, which indicates that they are meant for usage by root only.

This doesn't make sense - strfile is needed for users who maintain their own collection of fortunes (like my mail signature collection) and perfectly works for non-root users, therefore I see no reason why it should be in sbin.
                                                                                                                                                                                                   
I don't have such a strong opinion about unstr (because personally I don't need/use it), but IMHO it also should be in /usr/bin instead of sbin.

To fix this, replace the two `sbin` in `fortune-mod/CMakeLists.txt` with `bin`.

*) I noticed this when the openSUSE package was updated to 2.6.2, but since the previous packaged version was 1.99, the sbin path was possibly introduced earlier.

**Comment by shlomif** [comment]
@cboltz : thanks! Fixed in v2.10.0.
