### ISSUE TITLE
Shlomif_Common cmake module missing

### ISSUE THREAD

**Issue by ImNtReal** [shlomif/fortune-mod#5]
We seem to be missing the Shlomif_Common cmake module:

CMake Error at CMakeLists.txt:5 (INCLUDE):
  include could not find load file:

    Shlomif_Common

CMake Error at CMakeLists.txt:7 (SHLOMIF_COMMON_SETUP):
  Unknown CMake command "SHLOMIF_COMMON_SETUP".

**Comment by shlomif** [comment]
Hi! Happy new year!

This is intentional, see http://www.shlomifish.org/meta/FAQ/#Shlomif_Common_cmake and the travis.yml file - https://github.com/shlomif/fortune-mod/blob/master/.travis.yml . Note that it is present in the source releases.

Closing.
