### ISSUE TITLE
Only two pratchett quotes

### ISSUE THREAD

**Issue by einarjh** [shlomif/fortune-mod#53]
I just tried fortune for the first time in what must be ten years, and did a list of the various dat files. I was pleased to discover that there was a separate file for Pratchett quotes, and tried it out. Got the same quote three times in a row, inspected the file, and discovered that there are in fact only two quotes in the file. Though they are both good quotes, this looks like a bug to me.

**Comment by shlomif** [comment]
On Thu, 17 Jun 2021 10:48:34 -0700
einarjh ***@***.***> wrote:

> I just tried fortune for the first time in what must be ten years, and did a
> list of the various dat files. I was pleased to discover that there was a
> separate file for Pratchett quotes, and tried it out. Got the same quote
> three times in a row, inspected the file, and discovered that there are in
> fact only two quotes in the file. Though they are both good quotes, this
> looks like a bug to me.
> 

Hi!

these are what the debian package contained. patches under the origbsd licence
are welcome

-- 

Shlomi Fish       https://www.shlomifish.org/
My Photos - https://www.flickr.com/photos/shlomif/

When a FLOSS developer says they will work on something, he or she means
“maybe”.
    — https://www.shlomifish.org/humour/fortunes/osp_rules.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
Closing as stale due to lack of response. @einarjh and all: pullreqs are welcome.
