### ISSUE TITLE
Ferengi Rules of Acquisition

### ISSUE THREAD

**Issue by fonic** [shlomif/fortune-mod#59]
Hi, I came here to offer a pull request to add the _Ferengi Rules of Acquisiton_, only to find that they have already been added just a couple of days ago - what a weird coincidence...

However, the contents that were merged contain lots of typos and other errors (presumably, they were pulled from the [same source](https://projectsanctuary.com/the_complete_ferengi_rules_of_acquisition.htm) that I used).

I have created a cleaned up version that is also closer to the style of how the rules are usually recited within Star Trek episodes:
[froas-biglist-out.txt](https://github.com/shlomif/fortune-mod/files/7774702/froas-biglist-out.txt)

Also, I'd like to point out that this seems to be an _unofficial_ list - I couldn't find any indication that there ever was an official, comprehensive list of all 280+ rules. Thus, I also created a list based on [these contents ](https://gist.github.com/darkyen/120c46739985ebf3b39b) which include references to sources:
[froas-gistlist-out.txt](https://github.com/shlomif/fortune-mod/files/7774703/froas-gistlist-out.txt)

Let me know what you think.

**Comment by shlomif** [comment]
Hi!

On Fri, 24 Dec 2021 07:26:31 -0800
fonic ***@***.***> wrote:

> Hi, I came here to offer a pull request to add the _Ferengi Rules of
> Acquisiton_, only to find that they have already been added just a couple of
> days ago - what a weird coincidence...
> 
> However, the contents that were merged contain lots of typos and other errors
> (presumably, they were pulled from the [same
> source](https://projectsanctuary.com/the_complete_ferengi_rules_of_acquisition.htm)
> that I used).
> 
> I have created a cleaned up version that is also closer to the style of how
> the rules are usually recited within Star Trek episodes:
> [froas-biglist-out.txt](https://github.com/shlomif/fortune-mod/files/7774702/froas-biglist-out.txt)
> 
> Also, I'd like to point out that this seems to be an _unofficial_ list - I
> couldn't find any indication that there ever was an official, comprehensive
> list of all 280+ rules. Thus, I also created a list based on [these contents
> ](https://gist.github.com/darkyen/120c46739985ebf3b39b) which include
> references to sources:
> [froas-gistlist-out.txt](https://github.com/shlomif/fortune-mod/files/7774703/froas-gistlist-out.txt)
> 

I like the list with references better (given
https://en.wikiquote.org/wiki/Bill_Gates#Misattributed / etc. ), so feel free
to send a pull-req. Just note that the tests will fail if lines are too long or
on trailing space. Thanks!

> Let me know what you think.
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/MQHVF3 - The Atom Text Editor edits a 2,000,001B file

Chuck Norris once wrote a 10 million lines C++ program in Microsoft Notepad
without having to use the backspace key. And it compiled without errors or
warnings, and was 100% bug‐free.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by fonic** [comment]
I like the list with the references better, too - it may be less content, but correct/canon. Also, the references give it a nice touch.

I think I'll create a final list based on this (that's probably the source for the GIST file anyway):
https://memory-beta.fandom.com/wiki/Ferengi_Rules_of_Acquisition

**Comment by fonic** [comment]
Closed by #60.
