### ISSUE TITLE
Compiling ipk for OpenWRT failed

### ISSUE THREAD

**Issue by 1o1o1** [shlomif/fortune-mod#61]
Compiling ipk for OpenWRT failed
is it possible make fortune for OpenWRT? 
is it really possible or not in principle?

make[5]: Entering directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
[  0%] Building C object CMakeFiles/strfile.dir/util/strfile.c.o
[  1%] Linking C executable strfile
make[5]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
[  1%] Built target strfile
make[5]: Entering directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
Scanning dependencies of target randstr
make[5]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
make[5]: Entering directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
[  1%] Building C object CMakeFiles/randstr.dir/util/randstr.c.o
[  2%] Linking C executable randstr
make[5]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
[  2%] Built target randstr
make[5]: Entering directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
Scanning dependencies of target fortune
make[5]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
make[5]: Entering directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
[  2%] Building C object CMakeFiles/fortune.dir/fortune/fortune.c.o
[  2%] Linking C executable fortune
/home/dima/OpenWRT/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: cannot open output file fortune: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/fortune.dir/build.make:83: recipe for target 'fortune' failed
make[5]: *** [fortune] Error 1
make[5]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
CMakeFiles/Makefile2:169: recipe for target 'CMakeFiles/fortune.dir/all' failed
make[4]: *** [CMakeFiles/fortune.dir/all] Error 2
make[4]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
Makefile:70: recipe for target '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1/.built' failed
make[2]: *** [/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1/.built] Error 2
make[2]: Leaving directory '/home/dima/OpenWRT/openwrt/feeds/packages/utils/fortune-mod'
time: package/feeds/packages/fortune-mod/compile#0.88#0.36#1.18
package/Makefile:111: recipe for target 'package/feeds/packages/fortune-mod/compile' failed
make[1]: *** [package/feeds/packages/fortune-mod/compile] Error 2
make[1]: Leaving directory '/home/dima/OpenWRT/openwrt'
/home/dima/OpenWRT/openwrt/include/toplevel.mk:225: recipe for target 'package/fortune-mod/compile' failed
make: *** [package/fortune-mod/compile] Error 2

**Comment by shlomif** [comment]
Hi,

please use separate bindir from srcdir

On Tue, 11 Jan 2022 03:51:15 -0800
1o1o1 ***@***.***> wrote:

> Compiling ipk for OpenWRT failed
> is it possible make fortune for OpenWRT? 
> is it really possible or not in principle?
> 
> 
> make[5]: Entering directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> [  0%] Building C object CMakeFiles/strfile.dir/util/strfile.c.o [  1%]
> Linking C executable strfile make[5]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> [  1%] Built target strfile make[5]: Entering directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> Scanning dependencies of target randstr make[5]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> make[5]: Entering directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> [  1%] Building C object CMakeFiles/randstr.dir/util/randstr.c.o [  2%]
> Linking C executable randstr make[5]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> [  2%] Built target randstr make[5]: Entering directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> Scanning dependencies of target fortune make[5]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> make[5]: Entering directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> [  2%] Building C object CMakeFiles/fortune.dir/fortune/fortune.c.o [  2%]
> Linking C executable fortune
> /home/dima/OpenWRT/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld:
> cannot open output file fortune: Is a directory collect2: error: ld returned
> 1 exit status CMakeFiles/fortune.dir/build.make:83: recipe for target
> 'fortune' failed make[5]: *** [fortune] Error 1 make[5]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> CMakeFiles/Makefile2:169: recipe for target 'CMakeFiles/fortune.dir/all'
> failed make[4]: *** [CMakeFiles/fortune.dir/all] Error 2 make[4]: Leaving
> directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> Makefile:151: recipe for target 'all' failed make[3]: *** [all] Error 2
> make[3]: Leaving directory
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1'
> Makefile:70: recipe for target
> '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1/.built'
> failed make[2]: ***
> [/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.6.1/.built]
> Error 2 make[2]: Leaving directory
> '/home/dima/OpenWRT/openwrt/feeds/packages/utils/fortune-mod' time:
> package/feeds/packages/fortune-mod/compile#0.88#0.36#1.18
> package/Makefile:111: recipe for target
> 'package/feeds/packages/fortune-mod/compile' failed make[1]: ***
> [package/feeds/packages/fortune-mod/compile] Error 2 make[1]: Leaving
> directory '/home/dima/OpenWRT/openwrt'
> /home/dima/OpenWRT/openwrt/include/toplevel.mk:225: recipe for target
> 'package/fortune-mod/compile' failed make: *** [package/fortune-mod/compile]
> Error 2
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - https://shlom.in/selina

Daniel: Hello ladies, may I join you?
Buffy: Well, we’re having a girls’ talk, but… sure!
    — https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by 1o1o1** [comment]
It's cross compiling for OpenWRT system :)

**Comment by 1o1o1** [comment]
v 3.12.0 

-- Check for working CXX compiler: /home/dima/OpenWRT/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-musl-g++
-- Check for working CXX compiler: /home/dima/OpenWRT/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-musl-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /home/dima/OpenWRT/openwrt/staging_dir/host/bin/perl (found version "5.26.1") 
-- Found PkgConfig: /home/dima/OpenWRT/openwrt/staging_dir/host/bin/pkg-config (found version "0.29.2") 
-- Performing Test FLAG_EXISTS_1
-- Performing Test FLAG_EXISTS_1 - Success
-- Performing Test FLAG_EXISTS_2
-- Performing Test FLAG_EXISTS_2 - Success
-- Looking for 3 include files stdbool.h, ..., recode.h
-- Looking for 3 include files stdbool.h, ..., recode.h - not found
CMake Warning at CMakeLists.txt:142 (MESSAGE):
  Cannot find recode.h anywhere; it is usually unnecessary, but you may opt
  to install a source release tarball of the recode library from
  https://github.com/rrthomas/recode


-- Looking for regex.h
-- Looking for regex.h - found
CMake Error: Attempt to add a custom rule to output "/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/datfiles/rules-of-acquisition.rule" which already has a custom rule.
-- Configuring incomplete, errors occurred!
See also "/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/CMakeFiles/CMakeOutput.log".
See also "/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/CMakeFiles/CMakeError.log".
Makefile:69: recipe for target '/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/.configured_68b329da9893e34099c7d8ad5cb9c940' failed
make[2]: *** [/home/dima/OpenWRT/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/dima/OpenWRT/openwrt/feeds/packages/utils/fortune-mod'
time: package/feeds/packages/fortune-mod/compile#0.86#0.27#1.88
package/Makefile:111: recipe for target 'package/feeds/packages/fortune-mod/compile' failed
make[1]: *** [package/feeds/packages/fortune-mod/compile] Error 2
make[1]: Leaving directory '/home/dima/OpenWRT/openwrt'
/home/dima/OpenWRT/openwrt/include/toplevel.mk:225: recipe for target 'package/fortune-mod/compile' failed
make: *** [package/fortune-mod/compile] Error 2

**Comment by 1o1o1** [comment]
The last failure  :)

ESTDIR="/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/ipkg-install"  install;
make[3]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[4]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
Scanning dependencies of target strfile
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
[  5%] Building C object CMakeFiles/strfile.dir/util/strfile.c.o
[ 11%] Linking C executable strfile
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
[ 11%] Built target strfile
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
Scanning dependencies of target randstr
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
[ 17%] Building C object CMakeFiles/randstr.dir/util/randstr.c.o
[ 23%] Linking C executable randstr
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
[ 23%] Built target randstr
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
Scanning dependencies of target fortune
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[5]: Entering directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
[ 29%] Building C object CMakeFiles/fortune.dir/fortune/fortune.c.o
[ 35%] Linking C executable fortune
/home/adminus/lede/19.07.8/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: cannot open output file fortune: Is a directory
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/fortune.dir/build.make:84: fortune] Error 1
make[5]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[4]: *** [CMakeFiles/Makefile2:168: CMakeFiles/fortune.dir/all] Error 2
make[4]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[3]: *** [Makefile:152: all] Error 2
make[3]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0'
make[2]: *** [Makefile:76: /home/adminus/lede/19.07.8/openwrt/build_dir/target-mips_24kc_musl/fortune-mod-3.12.0/.built] Error 2
make[2]: Leaving directory '/home/adminus/lede/19.07.8/openwrt/feeds/packages/utils/fortune-mod'
time: package/feeds/packages/fortune-mod/compile#1.50#0.40#2.12
make[1]: *** [package/Makefile:113: package/feeds/packages/fortune-mod/compile] Error 2
make[1]: Leaving directory '/home/adminus/lede/19.07.8/openwrt'
make: *** [/home/adminus/lede/19.07.8/openwrt/include/toplevel.mk:227: package/fortune-mod/compile] Ошибка 2

**Comment by shlomif** [comment]
@1o1o1 : how are you invoking cmake? `cmake .` is a bad idea,

**Comment by shlomif** [comment]
Closing . i can reopen.
