### ISSUE TITLE
Incorrect Verbage

### ISSUE THREAD

**Issue by JackLimes** [shlomif/fortune-mod#63]
mittsquinter, adj.:
	A ballplayer who looks into his glove after missing the ball, as
	if, somehow, the cause of the error lies there.
		-- "Sniglets", Rich Hall & Friends

Is the fortune with the issue. It describes a mittsquinter as an adjective but then goes on to describe a noun.

**Comment by shlomif** [comment]
fixed in https://github.com/shlomif/fortune-mod/commit/ca4111b0c3b7725a61704d163f57eda87fb0a84d .thanks

**Comment by shlomif** [comment]
Released in v3.14.0
