### ISSUE TITLE
I need help and fix for `fortune with cowthink`

### ISSUE THREAD

**Issue by MiChaelinzo** [shlomif/fortune-mod#64]
<img width="473" alt="CowthinkScreenshot 2022-03-02 134241" src="https://user-images.githubusercontent.com/68110223/156346984-1cc94f47-d79d-4564-b5a3-e66c30043841.png">

**Comment by shlomif** [comment]
hi, see https://github.com/shlomif/how-to-share-code-online

**Comment by MiChaelinzo** [comment]
`/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.12.1-git20200711.33e2d80-dfsg1-0.6 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-GZpiDA-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/fortune", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fortune==1.1.0' distribution was not found and is required by the application
Usage: /usr/local/bin/cowthink [-e eye_string] [-f cowfile] [-h] [-l] [-n] [-T tongue_string] [-W column] [-bdgpstwy] text

If any command-line arguments are left over after all switches have been processed, they become the cow's message.

If the program is invoked as cowthink then the cow will think its message instead of saying it.

Options:
  -b  Mode: Borg                                                                                                                                  
  -d  Mode: Dead                                                                                                                                  
  -g  Mode: Greedy                                                                                                                                
  -p  Mode: Paranoia                                                                                                                              
  -s  Mode: Stoned                                                                                                                                
  -t  Mode: Tired                                                                                                                                 
  -w  Mode: Wired                                                                                                                                 
  -y  Mode: Youthful                                                                                                                              
  -e  Select the appearance of the cow's eyes.                                                                                                      [default: "oo"]
  -T  The tongue is configurable similarly to the eyes through -T and tongue_string.                                                                [default: "  "]
  -h  Display this help message                                                                                                                   
  -n  If it is specified, the given message will not be word-wrapped.                                                                             
  -W  Specifies roughly where the message should be wrapped. The default is equivalent to -W 40 i.e. wrap words at or before the 40th column.       [default: 40]
  -f  Specifies a cow picture file (''cowfile'') to use. It can be either a path to a cow file or the name of one of cows included in the package.  [default: "default"]
  -r  Select a random cow                                                                                                                         
  -l  List all cowfiles included in this package.      `

**Comment by shlomif** [comment]
Please try https://pypi.org/project/fortune/ . HTH.
