### ISSUE TITLE
‘Stupid idiot users’ insults outside `off`

### ISSUE THREAD

**Issue by emixa-d** [shlomif/fortune-mod#65]
> %
> User n.:
>         A programmer who will believe anything you tell him.
> %
> user, n.:
>         The word computer professionals use when they mean "idiot."
>                 -- Dave Barry, "Claw Your Way to the Top"
>
> [I always thought "computer professional" was the phrase hackers used
>  when they meant "idiot."  Ed.]

These two seem rather rude to users of fortune-mod (including ‘computer professionals’
because it implies they are, as a rule, rude).  Could they be moved to `off` or removed?

**Comment by shlomif** [comment]
closing due to lack-of-reply.
