### ISSUE TITLE
pets duplicates the same fortune twice

### ISSUE THREAD

**Issue by sjlongland** [shlomif/fortune-mod#66]
https://github.com/shlomif/fortune-mod/blob/4d82f4b63b562e17ab8b6eb8b72b9fe16b328002/fortune-mod/datfiles/pets#L187-L192

Little nit to clean up, looks like the same fortune cookie is repeated twice for some reason.

No patch, but `sed -i -e '187,189 d' fortune-mod/datfiles/pets` should clean it up.

**Comment by shlomif** [comment]
fixed
