### ISSUE TITLE
Review patches from Gentoo

### ISSUE THREAD

**Issue by candrews** [shlomif/fortune-mod#7]
Gentoo is carrying two patches against fortune. I bet most of these changes should be incorporated upstream.

https://github.com/gentoo/gentoo/blob/1c79f4dc1b1a367ecfc9324bf50f2558efdb2c45/games-misc/fortune-mod/files/01_all_fortune_all-fix.patch
https://github.com/gentoo/gentoo/blob/1c79f4dc1b1a367ecfc9324bf50f2558efdb2c45/games-misc/fortune-mod/files/fortune-mod-1.99.1-gentoo.patch

**Comment by shlomif** [comment]
The patches were incorporated here. Thanks!
