### ISSUE TITLE
Typo in fortune

### ISSUE THREAD

**Issue by sflitman** [shlomif/fortune-mod#70]
"There is also a thriving independent student movement in
Poland, and thus there is a strong possibility (though no
guarantee) of making an EARN-Poland link, should it ever come
about, a genuine link - not a vacuum cleaner attachment for a
Bloc information gathering apparatus rationed to trusted
apparatchiks."
-- David Phillips, SUNY at Buffalo, about establishing a
   gateway from EARN (**Eurpoean** Academic Research Network)
   to Poland

**Comment by shlomif** [comment]
@sflitman : what is the typo?

**Comment by modem7** [comment]
> @sflitman : what is the typo?

Looks like it's: "Eurpoean".

Second to last line.
