### ISSUE TITLE
Set up a PPA ("Personal Package Archive") for Ubuntu / etc.

### ISSUE THREAD

**Issue by modem7** [shlomif/fortune-mod#71]
Is there the potential for a PPA that we can add for the latest versions rather than building from source?

Currently, on Ubuntu 22.04 the version is 1.99.1 which seems quite outdated.

**Comment by shlomif** [comment]
@modem7 : hi. 1.99.1 is very outdated. A PPA will be nice, but the dpkg/debian/etc. ecosystem gives me nightmares and the new fortune-mod has some build-deps. You can peruse https://src.fedoraproject.org/rpms/fortune-mod as a reference,

**Comment by modem7** [comment]
Would cross compiling via github actions or similar be a potential solution in the meantime?

**Comment by shlomif** [comment]
@modem7 

> Could cross compiling via github actions or similar be a potential solution in the meantime?

I presume it could. pull-reqs / patches are welcome.

**Comment by shlomif** [comment]
For every one that is interested in setting up an Ubuntu/etc. PPA note that I made some headway using the script here: https://github.com/shlomif/fortune-mod/blob/master/scripts/debian-packaging/build-fortune-mod-debian-package--using-docker.pl . It uses Docker. Now I am stuck with a gnupg/pinentry issue.

**Comment by shlomif** [comment]
Mark as "enhancement" because it isn't a showstopper.

**Comment by Sweeistaken** [comment]
Helly, I can help with this issue, but I'm not familiar with PPA's. I believe my own repository would be fine as long as I convert it into a trivial repo

**Comment by shlomif** [comment]
> Hello, I can help with this issue, but I'm not familiar with PPA's. I believe my own repository would be fine as long as I convert it into a trivial repo

Hi @Sweeistaken !

Thanks for your enthusiasm! A repo of any kind that will be usable by recnt-ish ubuntu / debian / mint / etc. users will be a step forward. (And there is the `curl .. | bash -` hacky install proc.)

For your info, I think my docker-based scriptology builds the binary pkgs and installs them.

**Comment by modem7** [comment]
Cloudsmith might be a good choice if there's one lacking.

**Comment by Sweeistaken** [comment]
> > Hello, I can help with this issue, but I'm not familiar with PPA's. I believe my own repository would be fine as long as I convert it into a trivial repo
> 
> Hi @Sweeistaken !
> 
> Thanks for your enthusiasm! A repo of any kind that will be usable by recnt-ish ubuntu / debian / mint / etc. users will be a step forward. (And there is the `curl .. | bash -` hacky install proc.)
> 
> For your info, I think my docker-based scriptology builds the binary pkgs and installs them.

Hi, I've been trying to build this application for a while, doesn't seem this repository has a build guide, I've tried this, and it's going pretty successful.
```bash
$ wget https://github.com/shlomif/fortune-mod/releases/download/fortune-mod-3.22.0/fortune-mod-3.22.0.tar.xz
$ xz -d fortune-mod-3.22.0.tar.xz
$ tar -xf fortune-mod-3.22.0.tar
$ cd fortune-mod-3.22.0
$ mkdir build && cd build
$ cmake ..
$ make
$ export DESTDIR="$HOME/test" && make install
```

**Comment by Sweeistaken** [comment]
I've tried packaging my build of fortune-mod, but I get this:
```
$ sudo apt install ./fortune-mod.deb
$ fortune
fortune: error while loading shared libraries: librecode.so.0: cannot open shared object file: No such file or directory
$ sudo apt install librecode3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  g++-12 libabsl20220623 libcbor0.8 libdrm-nouveau2 libdrm-radeon1 libgphoto2-l10n libjim0.81 libnsl-dev
  libpthread-stubs0-dev libsensors-config libsensors5 libstdc++-12-dev libsub-override-perl libtirpc-dev python3-six
  vlc-l10n
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  librecode3
0 upgraded, 1 newly installed, 0 to remove and 420 not upgraded.
Need to get 232 kB of archives.
After this operation, 1,389 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian testing/main amd64 librecode3 amd64 3.7.14-1 [232 kB]
Fetched 232 kB in 0s (716 kB/s)
Selecting previously unselected package librecode3:amd64.
(Reading database ... 218777 files and directories currently installed.)
Preparing to unpack .../librecode3_3.7.14-1_amd64.deb ...
Unpacking librecode3:amd64 (3.7.14-1) ...
Setting up librecode3:amd64 (3.7.14-1) ...
Processing triggers for libc-bin (2.40-3) ...
$ fortune
fortune: error while loading shared libraries: librecode.so.0: cannot open shared object file: No such file or directory
```

the problem might be that I built the program on Debian stable while the VM I'm testing it in uses Debian Testing.

**Comment by Sweeistaken** [comment]
Hi, I have successfully uploaded the latest version of this program to my APT Repository,
https://swee.codes/linuxrepos

**Comment by shlomif** [comment]
@Sweeistaken : hi! Good job. I'll try to test your binary package in ubuntu/etc. docker containers soon. Thanks!

Re the documenting of the build process: it is divinable from the CI process, and based on https://www.shlomifish.org/philosophy/computers/software-management/perfect-workplace/#soft-eng-methods-to-avoid and similar, docs (even comments) tends to become outofdate.

**Comment by Sweeistaken** [comment]
I have tested my build of this project on Debian Stable, Debian Testing (WSL), and Ubuntu (WSL).  
Here are my results:

* Debian Stable and Ubuntu install and run the application correctly
* However, Debian Testing is unable to run/install it because librecode0 is replaced to librecode3 on the testing/unstalbe repository.

**Comment by shlomif** [comment]
Fixed now. thanks @Sweeistaken / etc.
