### ISSUE TITLE
Typo in fortune

### ISSUE THREAD

**Issue by sflitman** [shlomif/fortune-mod#72]
Ballistophobia:
 	Fear of bullets;
 Otophobia:
 	Fear of opening one's eyes.
 Peccatophobia:
 	Fear of sinning.
 Taphephobia:
 	Fear of being buried alive.
 Sitophobia:
 	Fear of food.
 **Trichophobbia**:
 	Fear of hair.
 Vestiphobia:
 	Fear of clothing.

Should be Trichophobia

**Comment by shlomif** [comment]
Hi! This was already fixed in:

commit 778847aabd0a244ff6ec2f7c52de1cf43a8b093e
Author: kdex <kdex@kdex.de>
Date:   Thu Nov 30 06:35:13 2017 +0100

    Fix numerous typos

there were some releases too since
