### ISSUE TITLE
backspace characters

### ISSUE THREAD

**Issue by komacke** [shlomif/fortune-mod#81]
There seem to be a number of places where the backspace character is in the fortune text. When the fortune is sent in email it's not recognized as text and gets converted to an attachment. Also some viewers show ^H instead of rendering the backspace of the text that was intended to be deleted. (vim displays the ^H whereas less interprets it.)

One example is the 'definitions' file.  Check "Gray's Law of Programming:". Also this picks up the affected lines:
grep  -P '[\b]' definitions

It seems like most examples originally had some underscore syntax that comes through as "_^H'.

Maybe we want this and fortune should have an option to convert the output into plain text?

**Comment by shlomif** [comment]
On Fri, 28 Apr 2023 07:39:14 -0700
Dave Koberstein ***@***.***> wrote:

> There seem to be a number of places where the backspace character is in the
> fortune text. When the fortune is sent in email it's not recognized as text
> and gets converted to an attachment. Also some viewers show ^H instead of
> rendering the backspace of the text that was intended to be deleted. (vim
> displays the ^H whereas less interprets it.)
> 
> One example is the 'definitions' file.  Check "Gray's Law of Programming:".
> Also this picks up the affected lines: grep  -P '[\b]' definitions
> 
> It seems like most examples originally had some underscore syntax that comes
> through as "_^H'.
> 
> Maybe we want this and fortune should have an option to convert the output
> into plain text?
> 

thanks! I'll see what we can do.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/lecture/C-and-CPP/bad-elements/

The Messiah will come when everybody assume his role.
    — https://www.shlomifish.org/philosophy/the-eternal-jew/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@komacke : should be fixed in git master

**Comment by komacke** [comment]
I'm a little late getting back to you. Thanks for the fix! Looks like it is coming through in the Fedora 39 release next week.
