### ISSUE TITLE
the command fortune -o doesn't work

### ISSUE THREAD

**Issue by stonedseeker** [shlomif/fortune-mod#82]
![image](https://github.com/shlomif/fortune-mod/assets/93109628/6148b75a-bec7-485e-9361-a757265d8020)

**Comment by shlomif** [comment]
@stonedseeker : hi! Some OS vendors build fortune-mod with `-DNO_OFFENSIVE=1` . Perhaps the error can be more helpful though.

https://www.goodreads.com/quotes/177682-programming-today-is-a-race-between-software-engineers-striving-to

**Comment by stonedseeker** [comment]
> @stonedseeker : hi! Some OS vendors build fortune-mod with `-DNO_OFFENSIVE=1` . Perhaps the error can be more helpful though.
> 
> https://www.goodreads.com/quotes/177682-programming-today-is-a-race-between-software-engineers-striving-to

I agree, still would have loved to see the results it would be getting me.

**Comment by shlomif** [comment]
> > @stonedseeker : hi! Some OS vendors build fortune-mod with `-DNO_OFFENSIVE=1` . Perhaps the error can be more helpful though.
> > https://www.goodreads.com/quotes/177682-programming-today-is-a-race-between-software-engineers-striving-to
> 
> I agree, still would have loved to see the results it would be getting me.

build fortune-mod from source then.
