### ISSUE TITLE
Installing from source doesn't seem to copy executable to install dir

### ISSUE THREAD

**Issue by benjamin051000** [shlomif/fortune-mod#85]
After configuring in cmake-gui with a custom prefix `~/utils/`, then running `make && make install`, it appears that the `fortune` binary isn't actually copied into `~/utils/bin/`. Is this correct behavior?

**Comment by shlomif** [comment]
@benjamin051000 : hi. please provide thed output of `find ~/utils/ -type f`.

**Comment by shlomif** [comment]
close due2lack of responsiveness
